In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [19]:
df=pd.read_csv("D:\\Data science\\py\ML\\2_linear_reg_multivariate\\homeprices.csv")
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [20]:
df.describe()

area  bedrooms        age          price
count     6.000000   5.00000   6.000000       6.000000
mean   3416.666667   4.20000  16.500000  648333.333333
std     587.934237   1.30384   8.288546  109117.673484
min    2600.000000   3.00000   8.000000  550000.000000
25%    3050.000000   3.00000   9.750000  572500.000000
50%    3400.000000   4.00000  16.500000  602500.000000
75%    3900.000000   5.00000  19.500000  722500.000000
max    4100.000000   6.00000  30.000000  810000.000000

In [21]:
round(df.bedrooms.mean())

4

In [22]:
df.bedrooms=df.bedrooms.fillna(round(df.bedrooms.mean()))


In [23]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [24]:
#Model
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [25]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [26]:
reg.intercept_

221323.00186540408

In [27]:
reg.predict([[1275,3,6]])

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([414978.94812365])

In [31]:
reg.predict([[10000,20,5]])

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1793566.43330237])

In [35]:
#formula for multi variable
# y(price)=m1*sqrft+m2*bedrooms+m3*age+intercept
112.06244194*4000+23388.88007794*5+-3231.71790863*8+221323.00186540408

760663.4267460641