In [4]:
!pip install word2number

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5567 sha256=4ff7c40d24474387f3c4033105ec967345babb8f0e6a6f115e252f604f6f5df0
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number


In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n

In [27]:
df=pd.read_csv("D:\\Data science\\py\ML\\2_linear_reg_multivariate\\\Exercise\\hiring.csv")
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [35]:
df.experience=df.experience.fillna('zero')

In [36]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [37]:
df.experience=df.experience.apply(w2n.word_to_num)

In [40]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].median())

In [41]:
"""model
 salary is dependent to below 3
interview_score(out of 10) --->independent
test_score(out of 10) --->independent
experience --->independent

"""
reg=linear_model.LinearRegression()
reg.fit(df[['interview_score(out of 10)','test_score(out of 10)','experience']],df['salary($)'])

LinearRegression()

In [42]:
reg.coef_

array([2205.24017467, 1845.70596798, 2812.95487627])

In [43]:
reg.intercept_

17737.263464337666

In [44]:
reg.predict([[8,8,8]])

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([72648.47161572])

In [45]:
reg.predict([[2,9,6]])

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([55636.82678311])

In [46]:
reg.predict([[12,10,10]])

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([90786.75400291])